const HSK_LEVELS = [
  { id: 1, name: "HSK 1 (3.0)", totalWords: 318, enabled: true },
  { id: 2, name: "HSK 2 (3.0)", totalWords: 0, enabled: false },
  { id: 3, name: "HSK 3 (3.0)", totalWords: 0, enabled: false },
];

const TOPICS = [
  { id: "hsk1_t1", level: 1, name: "Con người, Gia đình & Xưng hô", cn: "人物与家庭", count: 29 },
  { id: "hsk1_t2", level: 1, name: "Nghề nghiệp, Trường học & Y tế", cn: "职业、学习与医疗", count: 18 },
  { id: "hsk1_t3", level: 1, name: "Thời gian, Lịch trình & Thời tiết", cn: "时间与天气", count: 35 },
  { id: "hsk1_t4", level: 1, name: "Địa điểm, Không gian & Phương vị", cn: "地点与方位", count: 38 },
  { id: "hsk1_t5", level: 1, name: "Ẩm thực, Đồ ăn & Thức uống", cn: "饮食与餐饮", count: 19 },
  { id: "hsk1_t6", level: 1, name: "Đồ dùng, Phương tiện & Động vật", cn: "物品、交通与动物", count: 24 },
  { id: "hsk1_t7", level: 1, name: "Động từ hành động & Sinh hoạt thường ngày", cn: "动作与日常活动", count: 46 },
  { id: "hsk1_t8", level: 1, name: "Động từ năng nguyện, Phán đoán & Tâm lý", cn: "能愿、判断与心理动词", count: 15 },
  { id: "hsk1_t9", level: 1, name: "Tính từ miêu tả đặc điểm & Trạng thái", cn: "形容词", count: 15 },
  { id: "hsk1_t10", level: 1, name: "Số từ & Lượng từ", cn: "数词与量词", count: 24 },
  { id: "hsk1_t11", level: 1, name: "Đại từ chỉ định & Từ nghi vấn / Để hỏi", cn: "指示代词与疑问词", count: 23 },
  { id: "hsk1_t12", level: 1, name: "Phó từ, Trợ từ & Khẩu ngữ giao tiếp", cn: "副词、助词与日常交际", count: 32 },
];

const VOCAB_DATA = [
  { id: 1, level: 1, topicId: "hsk1_t1", hanzi: "大家", pinyin: "dàjiā", meaning: "mọi người" },
  { id: 2, level: 1, topicId: "hsk1_t1", hanzi: "们", pinyin: "men", meaning: "số nhiều" },
  { id: 3, level: 1, topicId: "hsk1_t1", hanzi: "您", pinyin: "nín", meaning: "ngài, ông, bà" },
  { id: 4, level: 1, topicId: "hsk1_t1", hanzi: "你们", pinyin: "nǐmen", meaning: "các bạn" },
  { id: 5, level: 1, topicId: "hsk1_t1", hanzi: "我", pinyin: "wǒ", meaning: "tôi" },
  { id: 6, level: 1, topicId: "hsk1_t1", hanzi: "名字", pinyin: "míngzi", meaning: "tên" },
  { id: 7, level: 1, topicId: "hsk1_t1", hanzi: "人", pinyin: "rén", meaning: "người" },
  { id: 8, level: 1, topicId: "hsk1_t1", hanzi: "朋友", pinyin: "péngyou", meaning: "bạn bè" },
  { id: 9, level: 1, topicId: "hsk1_t1", hanzi: "女朋友", pinyin: "nǚpéngyou", meaning: "bạn gái" },
  { id: 10, level: 1, topicId: "hsk1_t1", hanzi: "男朋友", pinyin: "nánpéngyou", meaning: "bạn trai" },
  { id: 11, level: 1, topicId: "hsk1_t1", hanzi: "她", pinyin: "tā", meaning: "cô ấy" },
  { id: 12, level: 1, topicId: "hsk1_t1", hanzi: "他", pinyin: "tā", meaning: "anh ấy" },
  { id: 13, level: 1, topicId: "hsk1_t1", hanzi: "它", pinyin: "tā", meaning: "nó" },
  { id: 14, level: 1, topicId: "hsk1_t1", hanzi: "姐姐", pinyin: "jiějie", meaning: "chị gái" },
  { id: 15, level: 1, topicId: "hsk1_t1", hanzi: "我们", pinyin: "wǒmen", meaning: "chúng tôi, chúng ta" },
  { id: 16, level: 1, topicId: "hsk1_t1", hanzi: "哥哥", pinyin: "gēge", meaning: "anh trai" },
  { id: 17, level: 1, topicId: "hsk1_t1", hanzi: "爸爸", pinyin: "bàba", meaning: "bố" },
  { id: 18, level: 1, topicId: "hsk1_t1", hanzi: "妈妈", pinyin: "māma", meaning: "mẹ" },
  { id: 19, level: 1, topicId: "hsk1_t1", hanzi: "妹妹", pinyin: "mèimei", meaning: "em gái" },
  { id: 20, level: 1, topicId: "hsk1_t1", hanzi: "儿子", pinyin: "érzi", meaning: "con trai (ý chỉ con cái)" },
  { id: 21, level: 1, topicId: "hsk1_t1", hanzi: "女儿", pinyin: "nǚ'ér", meaning: "con gái" },
  { id: 22, level: 1, topicId: "hsk1_t1", hanzi: "孩子", pinyin: "háizi", meaning: "con cái, trẻ nhỏ" },
  { id: 23, level: 1, topicId: "hsk1_t1", hanzi: "朋友", pinyin: "péngyou", meaning: "bạn" },
  { id: 24, level: 1, topicId: "hsk1_t1", hanzi: "女", pinyin: "nǚ", meaning: "nữ" },
  { id: 25, level: 1, topicId: "hsk1_t1", hanzi: "男", pinyin: "nán", meaning: "nam" },
  { id: 26, level: 1, topicId: "hsk1_t1", hanzi: "弟弟", pinyin: "dìdi", meaning: "em trai" },
  { id: 27, level: 1, topicId: "hsk1_t1", hanzi: "小朋友", pinyin: "xiǎopéngyou", meaning: "bạn nhỏ" },
  { id: 28, level: 1, topicId: "hsk1_t1", hanzi: "女士", pinyin: "nǚshì", meaning: "quý bà, quý cô" },
  { id: 29, level: 1, topicId: "hsk1_t1", hanzi: "家人", pinyin: "jiārén", meaning: "người nhà" },

  { id: 30, level: 1, topicId: "hsk1_t2", hanzi: "王老师", pinyin: "Wáng lǎoshī", meaning: "cô Vương" },
  { id: 31, level: 1, topicId: "hsk1_t2", hanzi: "学生", pinyin: "xuéshēng", meaning: "học sinh" },
  { id: 32, level: 1, topicId: "hsk1_t2", hanzi: "老师", pinyin: "lǎoshī", meaning: "giáo viên" },
  { id: 33, level: 1, topicId: "hsk1_t2", hanzi: "同学", pinyin: "tóngxué", meaning: "bạn học" },
  { id: 34, level: 1, topicId: "hsk1_t2", hanzi: "工作", pinyin: "gōngzuò", meaning: "công việc" },
  { id: 35, level: 1, topicId: "hsk1_t2", hanzi: "课", pinyin: "kè", meaning: "buổi, bài học" },
  { id: 36, level: 1, topicId: "hsk1_t2", hanzi: "病人", pinyin: "bìngrén", meaning: "bệnh nhân" },
  { id: 37, level: 1, topicId: "hsk1_t2", hanzi: "医生", pinyin: "yīshēng", meaning: "bác sĩ" },
  { id: 38, level: 1, topicId: "hsk1_t2", hanzi: "工作", pinyin: "gōngzuò", meaning: "công việc" },
  { id: 39, level: 1, topicId: "hsk1_t2", hanzi: "售货员", pinyin: "shòuhuòyuán", meaning: "nhân viên bán hàng" },
  { id: 40, level: 1, topicId: "hsk1_t2", hanzi: "读大学", pinyin: "dú dàxué", meaning: "học đại học" },
  { id: 41, level: 1, topicId: "hsk1_t2", hanzi: "大学生", pinyin: "dàxuéshēng", meaning: "sinh viên" },
  { id: 42, level: 1, topicId: "hsk1_t2", hanzi: "医", pinyin: "yī", meaning: "y" },
  { id: 43, level: 1, topicId: "hsk1_t2", hanzi: "生病", pinyin: "shēngbìng", meaning: "bị ốm, bị bệnh" },
  { id: 44, level: 1, topicId: "hsk1_t2", hanzi: "看病", pinyin: "kànbìng", meaning: "khám bệnh" },
  { id: 45, level: 1, topicId: "hsk1_t2", hanzi: "病", pinyin: "bìng", meaning: "bệnh" },
  { id: 46, level: 1, topicId: "hsk1_t2", hanzi: "药", pinyin: "yào", meaning: "thuốc" },
  { id: 47, level: 1, topicId: "hsk1_t2", hanzi: "服务员", pinyin: "fúwùyuán", meaning: "nhân viên phục vụ" },

  { id: 48, level: 1, topicId: "hsk1_t3", hanzi: "今年", pinyin: "jīnnián", meaning: "năm nay" },
  { id: 49, level: 1, topicId: "hsk1_t3", hanzi: "今天", pinyin: "jīntiān", meaning: "hôm nay" },
  { id: 50, level: 1, topicId: "hsk1_t3", hanzi: "年", pinyin: "nián", meaning: "năm" },
  { id: 51, level: 1, topicId: "hsk1_t3", hanzi: "月", pinyin: "yuè", meaning: "tháng" },
  { id: 52, level: 1, topicId: "hsk1_t3", hanzi: "号", pinyin: "hào", meaning: "ngày" },
  { id: 53, level: 1, topicId: "hsk1_t3", hanzi: "日", pinyin: "rì", meaning: "ngày (văn viết)" },
  { id: 54, level: 1, topicId: "hsk1_t3", hanzi: "星期", pinyin: "xīngqī", meaning: "thứ" },
  { id: 55, level: 1, topicId: "hsk1_t3", hanzi: "星期天", pinyin: "xīngqītiān", meaning: "chủ nhật" },
  { id: 56, level: 1, topicId: "hsk1_t3", hanzi: "星期日", pinyin: "xīngqīrì", meaning: "chủ nhật (văn viết)" },
  { id: 57, level: 1, topicId: "hsk1_t3", hanzi: "明天", pinyin: "míngtiān", meaning: "ngày mai" },
  { id: 58, level: 1, topicId: "hsk1_t3", hanzi: "现在", pinyin: "xiànzài", meaning: "bây giờ, hiện tại" },
  { id: 59, level: 1, topicId: "hsk1_t3", hanzi: "点", pinyin: "diǎn", meaning: "giờ" },
  { id: 60, level: 1, topicId: "hsk1_t3", hanzi: "早上", pinyin: "zǎoshang", meaning: "sáng sớm" },
  { id: 61, level: 1, topicId: "hsk1_t3", hanzi: "上午", pinyin: "shàngwǔ", meaning: "sáng" },
  { id: 62, level: 1, topicId: "hsk1_t3", hanzi: "中午", pinyin: "zhōngwǔ", meaning: "trưa" },
  { id: 63, level: 1, topicId: "hsk1_t3", hanzi: "下午", pinyin: "xiàwǔ", meaning: "chiều" },
  { id: 64, level: 1, topicId: "hsk1_t3", hanzi: "晚上", pinyin: "wǎnshang", meaning: "tối" },
  { id: 65, level: 1, topicId: "hsk1_t3", hanzi: "分", pinyin: "fēn", meaning: "phút" },
  { id: 66, level: 1, topicId: "hsk1_t3", hanzi: "半", pinyin: "bàn", meaning: "nửa, rưỡi" },
  { id: 67, level: 1, topicId: "hsk1_t3", hanzi: "分钟", pinyin: "fēnzhōng", meaning: "phút (lượng thời gian)" },
  { id: 68, level: 1, topicId: "hsk1_t3", hanzi: "白天", pinyin: "báitiān", meaning: "ban ngày" },
  { id: 69, level: 1, topicId: "hsk1_t3", hanzi: "时候", pinyin: "shíhou", meaning: "lúc, khi" },
  { id: 70, level: 1, topicId: "hsk1_t3", hanzi: "昨天", pinyin: "zuótiān", meaning: "hôm qua" },
  { id: 71, level: 1, topicId: "hsk1_t3", hanzi: "天气", pinyin: "tiānqì", meaning: "thời tiết" },
  { id: 72, level: 1, topicId: "hsk1_t3", hanzi: "天", pinyin: "tiān", meaning: "trời, ngày" },
  { id: 73, level: 1, topicId: "hsk1_t3", hanzi: "下雨", pinyin: "xiàyǔ", meaning: "mưa" },
  { id: 74, level: 1, topicId: "hsk1_t3", hanzi: "雨", pinyin: "yǔ", meaning: "cơn mưa" },
  { id: 75, level: 1, topicId: "hsk1_t3", hanzi: "冷", pinyin: "lěng", meaning: "lạnh" },
  { id: 76, level: 1, topicId: "hsk1_t3", hanzi: "下雪", pinyin: "xiàxuě", meaning: "tuyết rơi" },
  { id: 77, level: 1, topicId: "hsk1_t3", hanzi: "热", pinyin: "rè", meaning: "nóng" },
  { id: 78, level: 1, topicId: "hsk1_t3", hanzi: "中午", pinyin: "zhōngwǔ", meaning: "buổi trưa" },
  { id: 79, level: 1, topicId: "hsk1_t3", hanzi: "去年", pinyin: "qùnián", meaning: "năm ngoái" },
  { id: 80, level: 1, topicId: "hsk1_t3", hanzi: "小时", pinyin: "xiǎoshí", meaning: "tiếng đồng hồ" },
  { id: 81, level: 1, topicId: "hsk1_t3", hanzi: "时间", pinyin: "shíjiān", meaning: "thời gian" },
  { id: 82, level: 1, topicId: "hsk1_t3", hanzi: "早", pinyin: "zǎo", meaning: "sớm" },

  { id: 83, level: 1, topicId: "hsk1_t4", hanzi: "中国", pinyin: "Zhōngguó", meaning: "Trung Quốc" },
  { id: 84, level: 1, topicId: "hsk1_t4", hanzi: "法国", pinyin: "Fǎguó", meaning: "Pháp" },
  { id: 85, level: 1, topicId: "hsk1_t4", hanzi: "泰国", pinyin: "Tàiguó", meaning: "Thái Lan" },
  { id: 86, level: 1, topicId: "hsk1_t4", hanzi: "国", pinyin: "guó", meaning: "nước" },
  { id: 87, level: 1, topicId: "hsk1_t4", hanzi: "家", pinyin: "jiā", meaning: "nhà" },
  { id: 88, level: 1, topicId: "hsk1_t4", hanzi: "超市", pinyin: "chāoshì", meaning: "siêu thị" },
  { id: 89, level: 1, topicId: "hsk1_t4", hanzi: "那边", pinyin: "nàbian", meaning: "phía đó, phía bên kia" },
  { id: 90, level: 1, topicId: "hsk1_t4", hanzi: "饭店", pinyin: "fàndiàn", meaning: "nhà hàng" },
  { id: 91, level: 1, topicId: "hsk1_t4", hanzi: "电影院", pinyin: "diànyǐngyuàn", meaning: "rạp chiếu phim" },
  { id: 92, level: 1, topicId: "hsk1_t4", hanzi: "家里", pinyin: "jiā lǐ", meaning: "trong nhà" },
  { id: 93, level: 1, topicId: "hsk1_t4", hanzi: "医院", pinyin: "yīyuàn", meaning: "bệnh viện" },
  { id: 94, level: 1, topicId: "hsk1_t4", hanzi: "店", pinyin: "diàn", meaning: "tiệm" },
  { id: 95, level: 1, topicId: "hsk1_t4", hanzi: "后", pinyin: "hòu", meaning: "sau, sau khi" },
  { id: 96, level: 1, topicId: "hsk1_t4", hanzi: "房间", pinyin: "fángjiān", meaning: "phòng" },
  { id: 97, level: 1, topicId: "hsk1_t4", hanzi: "外", pinyin: "wài", meaning: "ngoài" },
  { id: 98, level: 1, topicId: "hsk1_t4", hanzi: "下", pinyin: "xià", meaning: "dưới" },
  { id: 99, level: 1, topicId: "hsk1_t4", hanzi: "学校", pinyin: "xuéxiào", meaning: "trường học" },
  { id: 100, level: 1, topicId: "hsk1_t4", hanzi: "书店", pinyin: "shūdiàn", meaning: "hiệu sách" },
  { id: 101, level: 1, topicId: "hsk1_t4", hanzi: "前", pinyin: "qián", meaning: "trước" },
  { id: 102, level: 1, topicId: "hsk1_t4", hanzi: "边", pinyin: "biān", meaning: "phía" },
  { id: 103, level: 1, topicId: "hsk1_t4", hanzi: "前边", pinyin: "qiánbian", meaning: "phía trước" },
  { id: 104, level: 1, topicId: "hsk1_t4", hanzi: "后边", pinyin: "hòubian", meaning: "phía sau" },
  { id: 105, level: 1, topicId: "hsk1_t4", hanzi: "里边", pinyin: "lǐbian", meaning: "phía trong" },
  { id: 106, level: 1, topicId: "hsk1_t4", hanzi: "外边", pinyin: "wàibian", meaning: "phía ngoài" },
  { id: 107, level: 1, topicId: "hsk1_t4", hanzi: "上边", pinyin: "shàngbian", meaning: "phía trên" },
  { id: 108, level: 1, topicId: "hsk1_t4", hanzi: "下边", pinyin: "xiàbian", meaning: "phía dưới" },
  { id: 109, level: 1, topicId: "hsk1_t4", hanzi: "家", pinyin: "jiā", meaning: "lượng từ (doanh nghiệp)" },
  { id: 110, level: 1, topicId: "hsk1_t4", hanzi: "这边", pinyin: "zhèbiān", meaning: "phía này" },
  { id: 111, level: 1, topicId: "hsk1_t4", hanzi: "这儿", pinyin: "zhèr", meaning: "chỗ này" },
  { id: 112, level: 1, topicId: "hsk1_t4", hanzi: "商店", pinyin: "shāngdiàn", meaning: "cửa hàng" },
  { id: 113, level: 1, topicId: "hsk1_t4", hanzi: "那儿", pinyin: "nàr", meaning: "chỗ kia" },
  { id: 114, level: 1, topicId: "hsk1_t4", hanzi: "饭店", pinyin: "fàndiàn", meaning: "nhà hàng" },
  { id: 115, level: 1, topicId: "hsk1_t4", hanzi: "大学", pinyin: "dàxué", meaning: "đại học" },
  { id: 116, level: 1, topicId: "hsk1_t4", hanzi: "那里", pinyin: "nàlǐ", meaning: "chỗ kia" },
  { id: 117, level: 1, topicId: "hsk1_t4", hanzi: "这里", pinyin: "zhèlǐ", meaning: "chỗ đó" },
  { id: 118, level: 1, topicId: "hsk1_t4", hanzi: "公司", pinyin: "gōngsī", meaning: "công ty" },
  { id: 119, level: 1, topicId: "hsk1_t4", hanzi: "上", pinyin: "shàng", meaning: "lên (xe, lầu)" },
  { id: 120, level: 1, topicId: "hsk1_t4", hanzi: "机场", pinyin: "jīchǎng", meaning: "sân bay" },

  { id: 121, level: 1, topicId: "hsk1_t5", hanzi: "做饭", pinyin: "zuòfàn", meaning: "nấu cơm" },
  { id: 122, level: 1, topicId: "hsk1_t5", hanzi: "面条儿", pinyin: "miàntiáor", meaning: "mì sợi" },
  { id: 123, level: 1, topicId: "hsk1_t5", hanzi: "饺子", pinyin: "jiǎozi", meaning: "sủi cảo" },
  { id: 124, level: 1, topicId: "hsk1_t5", hanzi: "菜", pinyin: "cài", meaning: "món ăn, rau" },
  { id: 125, level: 1, topicId: "hsk1_t5", hanzi: "牛奶", pinyin: "niúnǎi", meaning: "sữa bò" },
  { id: 126, level: 1, topicId: "hsk1_t5", hanzi: "吃", pinyin: "chī", meaning: "ăn" },
  { id: 127, level: 1, topicId: "hsk1_t5", hanzi: "晚饭", pinyin: "wǎnfàn", meaning: "bữa tối" },
  { id: 128, level: 1, topicId: "hsk1_t5", hanzi: "包子", pinyin: "bāozi", meaning: "bánh bao" },
  { id: 129, level: 1, topicId: "hsk1_t5", hanzi: "米饭", pinyin: "mǐfàn", meaning: "cơm trắng" },
  { id: 130, level: 1, topicId: "hsk1_t5", hanzi: "菜", pinyin: "cài", meaning: "món ăn, rau" },
  { id: 131, level: 1, topicId: "hsk1_t5", hanzi: "午饭", pinyin: "wǔfàn", meaning: "bữa trưa" },
  { id: 132, level: 1, topicId: "hsk1_t5", hanzi: "饭", pinyin: "fàn", meaning: "cơm, bữa cơm" },
  { id: 133, level: 1, topicId: "hsk1_t5", hanzi: "水果", pinyin: "shuǐguǒ", meaning: "hoa quả" },
  { id: 134, level: 1, topicId: "hsk1_t5", hanzi: "苹果", pinyin: "píngguǒ", meaning: "táo" },
  { id: 135, level: 1, topicId: "hsk1_t5", hanzi: "喝", pinyin: "hē", meaning: "uống" },
  { id: 136, level: 1, topicId: "hsk1_t5", hanzi: "水", pinyin: "shuǐ", meaning: "nước" },
  { id: 137, level: 1, topicId: "hsk1_t5", hanzi: "早饭", pinyin: "zǎofàn", meaning: "bữa sáng" },
  { id: 138, level: 1, topicId: "hsk1_t5", hanzi: "面包", pinyin: "miànbāo", meaning: "bánh mì" },
  { id: 139, level: 1, topicId: "hsk1_t5", hanzi: "鸡蛋", pinyin: "jīdàn", meaning: "trứng gà" },

  { id: 140, level: 1, topicId: "hsk1_t6", hanzi: "中文", pinyin: "Zhōngwén", meaning: "tiếng Trung" },
  { id: 141, level: 1, topicId: "hsk1_t6", hanzi: "电脑", pinyin: "diànnǎo", meaning: "máy tính" },
  { id: 142, level: 1, topicId: "hsk1_t6", hanzi: "手机号", pinyin: "shǒujīhào", meaning: "số điện thoại" },
  { id: 143, level: 1, topicId: "hsk1_t6", hanzi: "东西", pinyin: "dōngxi", meaning: "đồ, vật nói chung" },
  { id: 144, level: 1, topicId: "hsk1_t6", hanzi: "出租车", pinyin: "chūzūchē", meaning: "taxi" },
  { id: 145, level: 1, topicId: "hsk1_t6", hanzi: "电影", pinyin: "diànyǐng", meaning: "phim điện ảnh" },
  { id: 146, level: 1, topicId: "hsk1_t6", hanzi: "事", pinyin: "shì", meaning: "việc, chuyện" },
  { id: 147, level: 1, topicId: "hsk1_t6", hanzi: "猫", pinyin: "māo", meaning: "mèo" },
  { id: 148, level: 1, topicId: "hsk1_t6", hanzi: "桌子", pinyin: "zhuōzi", meaning: "bàn" },
  { id: 149, level: 1, topicId: "hsk1_t6", hanzi: "椅子", pinyin: "yǐzi", meaning: "ghế" },
  { id: 150, level: 1, topicId: "hsk1_t6", hanzi: "书", pinyin: "shū", meaning: "sách" },
  { id: 151, level: 1, topicId: "hsk1_t6", hanzi: "电视", pinyin: "diànshì", meaning: "TV" },
  { id: 152, level: 1, topicId: "hsk1_t6", hanzi: "狗", pinyin: "gǒu", meaning: "chó" },
  { id: 153, level: 1, topicId: "hsk1_t6", hanzi: "杯子", pinyin: "bēizi", meaning: "cốc" },
  { id: 154, level: 1, topicId: "hsk1_t6", hanzi: "钱", pinyin: "qián", meaning: "tiền" },
  { id: 155, level: 1, topicId: "hsk1_t6", hanzi: "衣服", pinyin: "yīfu", meaning: "quần áo" },
  { id: 156, level: 1, topicId: "hsk1_t6", hanzi: "车", pinyin: "chē", meaning: "xe" },
  { id: 157, level: 1, topicId: "hsk1_t6", hanzi: "问题", pinyin: "wèntí", meaning: "vấn đề" },
  { id: 158, level: 1, topicId: "hsk1_t6", hanzi: "杯子", pinyin: "bēizi", meaning: "cốc" },
  { id: 159, level: 1, topicId: "hsk1_t6", hanzi: "火车", pinyin: "huǒchē", meaning: "tàu hỏa" },
  { id: 160, level: 1, topicId: "hsk1_t6", hanzi: "字", pinyin: "zì", meaning: "chữ" },
  { id: 161, level: 1, topicId: "hsk1_t6", hanzi: "汉字", pinyin: "Hànzì", meaning: "chữ Hán" },
  { id: 162, level: 1, topicId: "hsk1_t6", hanzi: "汉语", pinyin: "Hànyǔ", meaning: "tiếng Hán" },
  { id: 163, level: 1, topicId: "hsk1_t6", hanzi: "飞机", pinyin: "fēijī", meaning: "máy bay" },

  { id: 164, level: 1, topicId: "hsk1_t7", hanzi: "请问", pinyin: "qǐngwèn", meaning: "xin hỏi" },
  { id: 165, level: 1, topicId: "hsk1_t7", hanzi: "认识", pinyin: "rènshi", meaning: "quen, nhận biết" },
  { id: 166, level: 1, topicId: "hsk1_t7", hanzi: "休息", pinyin: "xiūxi", meaning: "nghỉ ngơi" },
  { id: 167, level: 1, topicId: "hsk1_t7", hanzi: "做", pinyin: "zuò", meaning: "làm, nấu" },
  { id: 168, level: 1, topicId: "hsk1_t7", hanzi: "上班", pinyin: "shàngbān", meaning: "đi làm" },
  { id: 169, level: 1, topicId: "hsk1_t7", hanzi: "下班", pinyin: "xiàbān", meaning: "tan làm" },
  { id: 170, level: 1, topicId: "hsk1_t7", hanzi: "打电话", pinyin: "dǎ diànhuà", meaning: "gọi điện thoại" },
  { id: 171, level: 1, topicId: "hsk1_t7", hanzi: "去", pinyin: "qù", meaning: "đi, đi đến" },
  { id: 172, level: 1, topicId: "hsk1_t7", hanzi: "买", pinyin: "mǎi", meaning: "mua" },
  { id: 173, level: 1, topicId: "hsk1_t7", hanzi: "坐", pinyin: "zuò", meaning: "ngồi" },
  { id: 174, level: 1, topicId: "hsk1_t7", hanzi: "上课", pinyin: "shàngkè", meaning: "lên lớp" },
  { id: 175, level: 1, topicId: "hsk1_t7", hanzi: "下课", pinyin: "xiàkè", meaning: "tan lớp" },
  { id: 176, level: 1, topicId: "hsk1_t7", hanzi: "见", pinyin: "jiàn", meaning: "gặp" },
  { id: 177, level: 1, topicId: "hsk1_t7", hanzi: "看", pinyin: "kàn", meaning: "nhìn, đọc, xem" },
  { id: 178, level: 1, topicId: "hsk1_t7", hanzi: "上班", pinyin: "shàngbān", meaning: "đi làm" },
  { id: 179, level: 1, topicId: "hsk1_t7", hanzi: "看见", pinyin: "kànjiàn", meaning: "nhìn thấy" },
  { id: 180, level: 1, topicId: "hsk1_t7", hanzi: "到", pinyin: "dào", meaning: "đến, tới nơi" },
  { id: 181, level: 1, topicId: "hsk1_t7", hanzi: "学习", pinyin: "xuéxí", meaning: "học hành" },
  { id: 182, level: 1, topicId: "hsk1_t7", hanzi: "做", pinyin: "zuò", meaning: "làm" },
  { id: 183, level: 1, topicId: "hsk1_t7", hanzi: "读书", pinyin: "dúshū", meaning: "đọc sách, đi học" },
  { id: 184, level: 1, topicId: "hsk1_t7", hanzi: "唱", pinyin: "chàng", meaning: "hát" },
  { id: 185, level: 1, topicId: "hsk1_t7", hanzi: "歌", pinyin: "gē", meaning: "bài hát" },
  { id: 186, level: 1, topicId: "hsk1_t7", hanzi: "玩", pinyin: "wán", meaning: "chơi" },
  { id: 187, level: 1, topicId: "hsk1_t7", hanzi: "穿", pinyin: "chuān", meaning: "mặc" },
  { id: 188, level: 1, topicId: "hsk1_t7", hanzi: "找", pinyin: "zhǎo", meaning: "tìm" },
  { id: 189, level: 1, topicId: "hsk1_t7", hanzi: "开车", pinyin: "kāichē", meaning: "lái xe (ô tô)" },
  { id: 190, level: 1, topicId: "hsk1_t7", hanzi: "学", pinyin: "xué", meaning: "học" },
  { id: 191, level: 1, topicId: "hsk1_t7", hanzi: "起床", pinyin: "qǐchuáng", meaning: "thức dậy" },
  { id: 192, level: 1, topicId: "hsk1_t7", hanzi: "睡觉", pinyin: "shuìjiào", meaning: "đi ngủ" },
  { id: 193, level: 1, topicId: "hsk1_t7", hanzi: "睡", pinyin: "shuì", meaning: "ngủ" },
  { id: 194, level: 1, topicId: "hsk1_t7", hanzi: "问", pinyin: "wèn", meaning: "hỏi" },
  { id: 195, level: 1, topicId: "hsk1_t7", hanzi: "说", pinyin: "shuō", meaning: "nói" },
  { id: 196, level: 1, topicId: "hsk1_t7", hanzi: "来", pinyin: "lái", meaning: "đến" },
  { id: 197, level: 1, topicId: "hsk1_t7", hanzi: "回", pinyin: "huí", meaning: "về, trở về" },
  { id: 198, level: 1, topicId: "hsk1_t7", hanzi: "卖", pinyin: "mài", meaning: "bán" },
  { id: 199, level: 1, topicId: "hsk1_t7", hanzi: "打电话", pinyin: "dǎ diànhuà", meaning: "gọi điện thoại" },
  { id: 200, level: 1, topicId: "hsk1_t7", hanzi: "请", pinyin: "qǐng", meaning: "mời, xin hãy" },
  { id: 201, level: 1, topicId: "hsk1_t7", hanzi: "坐", pinyin: "zuò", meaning: "ngồi" },
  { id: 202, level: 1, topicId: "hsk1_t7", hanzi: "给", pinyin: "gěi", meaning: "cho" },
  { id: 203, level: 1, topicId: "hsk1_t7", hanzi: "开", pinyin: "kāi", meaning: "lái, chạy (xe)" },
  { id: 204, level: 1, topicId: "hsk1_t7", hanzi: "写", pinyin: "xiě", meaning: "viết" },
  { id: 205, level: 1, topicId: "hsk1_t7", hanzi: "听见", pinyin: "tīngjiàn", meaning: "nghe thấy" },
  { id: 206, level: 1, topicId: "hsk1_t7", hanzi: "说话", pinyin: "shuōhuà", meaning: "nói chuyện" },
  { id: 207, level: 1, topicId: "hsk1_t7", hanzi: "听", pinyin: "tīng", meaning: "nghe" },
  { id: 208, level: 1, topicId: "hsk1_t7", hanzi: "接", pinyin: "jiē", meaning: "đón" },
  { id: 209, level: 1, topicId: "hsk1_t7", hanzi: "住", pinyin: "zhù", meaning: "sống ở, ở (qua đêm)" },

  { id: 210, level: 1, topicId: "hsk1_t8", hanzi: "叫", pinyin: "jiào", meaning: "gọi, tên là" },
  { id: 211, level: 1, topicId: "hsk1_t8", hanzi: "是", pinyin: "shì", meaning: "là, phải là" },
  { id: 212, level: 1, topicId: "hsk1_t8", hanzi: "想", pinyin: "xiǎng", meaning: "nhớ / muốn" },
  { id: 213, level: 1, topicId: "hsk1_t8", hanzi: "有", pinyin: "yǒu", meaning: "có" },
  { id: 214, level: 1, topicId: "hsk1_t8", hanzi: "没有", pinyin: "méiyǒu", meaning: "không có" },
  { id: 215, level: 1, topicId: "hsk1_t8", hanzi: "会", pinyin: "huì", meaning: "biết" },
  { id: 216, level: 1, topicId: "hsk1_t8", hanzi: "喜欢", pinyin: "xǐhuan", meaning: "thích" },
  { id: 217, level: 1, topicId: "hsk1_t8", hanzi: "想", pinyin: "xiǎng", meaning: "muốn" },
  { id: 218, level: 1, topicId: "hsk1_t8", hanzi: "能", pinyin: "néng", meaning: "có thể" },
  { id: 219, level: 1, topicId: "hsk1_t8", hanzi: "知道", pinyin: "zhīdào", meaning: "biết" },
  { id: 220, level: 1, topicId: "hsk1_t8", hanzi: "要", pinyin: "yào", meaning: "muốn, cần, phải" },
  { id: 221, level: 1, topicId: "hsk1_t8", hanzi: "觉得", pinyin: "juéde", meaning: "cảm thấy, thấy" },
  { id: 222, level: 1, topicId: "hsk1_t8", hanzi: "可以", pinyin: "kěyǐ", meaning: "có thể, được" },
  { id: 223, level: 1, topicId: "hsk1_t8", hanzi: "不要", pinyin: "búyào", meaning: "đừng" },
  { id: 224, level: 1, topicId: "hsk1_t8", hanzi: "爱", pinyin: "ài", meaning: "yêu" },

  { id: 225, level: 1, topicId: "hsk1_t9", hanzi: "好", pinyin: "hǎo", meaning: "tốt" },
  { id: 226, level: 1, topicId: "hsk1_t9", hanzi: "高兴", pinyin: "gāoxìng", meaning: "vui vẻ" },
  { id: 227, level: 1, topicId: "hsk1_t9", hanzi: "忙", pinyin: "máng", meaning: "bận" },
  { id: 228, level: 1, topicId: "hsk1_t9", hanzi: "新", pinyin: "xīn", meaning: "mới" },
  { id: 229, level: 1, topicId: "hsk1_t9", hanzi: "好看", pinyin: "hǎokàn", meaning: "đẹp, ưa nhìn" },
  { id: 230, level: 1, topicId: "hsk1_t9", hanzi: "好吃", pinyin: "hǎochī", meaning: "ngon" },
  { id: 231, level: 1, topicId: "hsk1_t9", hanzi: "小", pinyin: "xiǎo", meaning: "nhỏ" },
  { id: 232, level: 1, topicId: "hsk1_t9", hanzi: "漂亮", pinyin: "piàoliang", meaning: "đẹp" },
  { id: 233, level: 1, topicId: "hsk1_t9", hanzi: "大", pinyin: "dà", meaning: "to lớn" },
  { id: 234, level: 1, topicId: "hsk1_t9", hanzi: "多", pinyin: "duō", meaning: "nhiều" },
  { id: 235, level: 1, topicId: "hsk1_t9", hanzi: "好听", pinyin: "hǎotīng", meaning: "nghe hay" },
  { id: 236, level: 1, topicId: "hsk1_t9", hanzi: "少", pinyin: "shǎo", meaning: "ít" },
  { id: 237, level: 1, topicId: "hsk1_t9", hanzi: "便宜", pinyin: "piányi", meaning: "rẻ" },
  { id: 238, level: 1, topicId: "hsk1_t9", hanzi: "贵", pinyin: "guì", meaning: "đắt" },
  { id: 239, level: 1, topicId: "hsk1_t9", hanzi: "好玩儿", pinyin: "hǎowánr", meaning: "chơi vui" },

  { id: 240, level: 1, topicId: "hsk1_t10", hanzi: "个", pinyin: "gè", meaning: "lượng từ (đọc là gè)" },
  { id: 241, level: 1, topicId: "hsk1_t10", hanzi: "口", pinyin: "kǒu", meaning: "lượng từ (đọc là kǒu)" },
  { id: 242, level: 1, topicId: "hsk1_t10", hanzi: "一", pinyin: "yī", meaning: "một" },
  { id: 243, level: 1, topicId: "hsk1_t10", hanzi: "二", pinyin: "èr", meaning: "hai" },
  { id: 244, level: 1, topicId: "hsk1_t10", hanzi: "三", pinyin: "sān", meaning: "ba" },
  { id: 245, level: 1, topicId: "hsk1_t10", hanzi: "四", pinyin: "sì", meaning: "bốn" },
  { id: 246, level: 1, topicId: "hsk1_t10", hanzi: "五", pinyin: "wǔ", meaning: "năm" },
  { id: 247, level: 1, topicId: "hsk1_t10", hanzi: "六", pinyin: "liù", meaning: "sáu" },
  { id: 248, level: 1, topicId: "hsk1_t10", hanzi: "七", pinyin: "qī", meaning: "bảy" },
  { id: 249, level: 1, topicId: "hsk1_t10", hanzi: "八", pinyin: "bā", meaning: "tám" },
  { id: 250, level: 1, topicId: "hsk1_t10", hanzi: "九", pinyin: "jiǔ", meaning: "chín" },
  { id: 251, level: 1, topicId: "hsk1_t10", hanzi: "十", pinyin: "shí", meaning: "mười" },
  { id: 252, level: 1, topicId: "hsk1_t10", hanzi: "岁", pinyin: "suì", meaning: "tuổi" },
  { id: 253, level: 1, topicId: "hsk1_t10", hanzi: "一些", pinyin: "yīxiē", meaning: "một ít, một vài" },
  { id: 254, level: 1, topicId: "hsk1_t10", hanzi: "些", pinyin: "xiē", meaning: "ít, chút (lượng từ số nhiều)" },
  { id: 255, level: 1, topicId: "hsk1_t10", hanzi: "只", pinyin: "zhī", meaning: "lượng từ (con vật)" },
  { id: 256, level: 1, topicId: "hsk1_t10", hanzi: "本", pinyin: "běn", meaning: "cuốn, quyển" },
  { id: 257, level: 1, topicId: "hsk1_t10", hanzi: "第", pinyin: "dì", meaning: "thứ (thứ tự)" },
  { id: 258, level: 1, topicId: "hsk1_t10", hanzi: "块", pinyin: "kuài", meaning: "đồng (ndt)" },
  { id: 259, level: 1, topicId: "hsk1_t10", hanzi: "斤", pinyin: "jīn", meaning: "nửa cân" },
  { id: 260, level: 1, topicId: "hsk1_t10", hanzi: "件", pinyin: "jiàn", meaning: "lượng từ quần áo" },
  { id: 261, level: 1, topicId: "hsk1_t10", hanzi: "元", pinyin: "yuán", meaning: "đồng (văn viết)" },
  { id: 262, level: 1, topicId: "hsk1_t10", hanzi: "一点儿", pinyin: "yìdiǎnr", meaning: "một chút" },
  { id: 263, level: 1, topicId: "hsk1_t10", hanzi: "一下", pinyin: "yíxià", meaning: "một chút" },

  { id: 264, level: 1, topicId: "hsk1_t11", hanzi: "什么", pinyin: "shénme", meaning: "gì, cái gì" },
  { id: 265, level: 1, topicId: "hsk1_t11", hanzi: "这", pinyin: "zhè", meaning: "đây / này" },
  { id: 266, level: 1, topicId: "hsk1_t11", hanzi: "谁", pinyin: "shéi", meaning: "ai" },
  { id: 267, level: 1, topicId: "hsk1_t11", hanzi: "哪", pinyin: "nǎ", meaning: "nào" },
  { id: 268, level: 1, topicId: "hsk1_t11", hanzi: "多少", pinyin: "duōshao", meaning: "bao nhiêu" },
  { id: 269, level: 1, topicId: "hsk1_t11", hanzi: "几", pinyin: "jǐ", meaning: "mấy" },
  { id: 270, level: 1, topicId: "hsk1_t11", hanzi: "多大", pinyin: "duōdà", meaning: "bao nhiêu tuổi" },
  { id: 271, level: 1, topicId: "hsk1_t11", hanzi: "哪儿", pinyin: "nǎr", meaning: "đâu" },
  { id: 272, level: 1, topicId: "hsk1_t11", hanzi: "怎么", pinyin: "zěnme", meaning: "sao, bằng cách nào" },
  { id: 273, level: 1, topicId: "hsk1_t11", hanzi: "那", pinyin: "nà", meaning: "kia, đó" },
  { id: 274, level: 1, topicId: "hsk1_t11", hanzi: "这些", pinyin: "zhèxiē", meaning: "những thứ này" },
  { id: 275, level: 1, topicId: "hsk1_t11", hanzi: "那些", pinyin: "nàxiē", meaning: "những thứ kia" },
  { id: 276, level: 1, topicId: "hsk1_t11", hanzi: "怎么样", pinyin: "zěnmeyàng", meaning: "thấy sao, như thế nào" },
  { id: 277, level: 1, topicId: "hsk1_t11", hanzi: "什么时候", pinyin: "shénme shíhou", meaning: "khi nào" },
  { id: 278, level: 1, topicId: "hsk1_t11", hanzi: "哪里", pinyin: "nǎlǐ", meaning: "chỗ nào" },
  { id: 279, level: 1, topicId: "hsk1_t11", hanzi: "这个", pinyin: "zhège", meaning: "cái này" },
  { id: 280, level: 1, topicId: "hsk1_t11", hanzi: "那个", pinyin: "nàge", meaning: "cái kia" },
  { id: 281, level: 1, topicId: "hsk1_t11", hanzi: "有些", pinyin: "yǒuxiē", meaning: "có một số" },
  { id: 282, level: 1, topicId: "hsk1_t11", hanzi: "有的", pinyin: "yǒude", meaning: "có cái, có người" },
  { id: 283, level: 1, topicId: "hsk1_t11", hanzi: "哪些", pinyin: "nǎxiē", meaning: "những cái nào" },
  { id: 284, level: 1, topicId: "hsk1_t11", hanzi: "哪个", pinyin: "nǎge", meaning: "cái nào" },
  { id: 285, level: 1, topicId: "hsk1_t11", hanzi: "几", pinyin: "jǐ", meaning: "vài, mấy" },
  { id: 286, level: 1, topicId: "hsk1_t11", hanzi: "那", pinyin: "nà", meaning: "thế thì" },

  { id: 287, level: 1, topicId: "hsk1_t12", hanzi: "你好", pinyin: "nǐ hǎo", meaning: "xin chào" },
  { id: 288, level: 1, topicId: "hsk1_t12", hanzi: "谢谢", pinyin: "xièxie", meaning: "cảm ơn" },
  { id: 289, level: 1, topicId: "hsk1_t12", hanzi: "不客气", pinyin: "bú kèqi", meaning: "đừng khách sáo" },
  { id: 290, level: 1, topicId: "hsk1_t12", hanzi: "再见", pinyin: "zàijiàn", meaning: "tạm biệt" },
  { id: 291, level: 1, topicId: "hsk1_t12", hanzi: "吗", pinyin: "ma", meaning: "phải không, hả" },
  { id: 292, level: 1, topicId: "hsk1_t12", hanzi: "不", pinyin: "bù", meaning: "không (phủ định)" },
  { id: 293, level: 1, topicId: "hsk1_t12", hanzi: "对不起", pinyin: "duìbuqǐ", meaning: "xin lỗi" },
  { id: 294, level: 1, topicId: "hsk1_t12", hanzi: "没关系", pinyin: "méi guānxi", meaning: "không sao" },
  { id: 295, level: 1, topicId: "hsk1_t12", hanzi: "没事", pinyin: "méi shì", meaning: "không có việc gì" },
  { id: 296, level: 1, topicId: "hsk1_t12", hanzi: "很", pinyin: "hěn", meaning: "rất" },
  { id: 297, level: 1, topicId: "hsk1_t12", hanzi: "也", pinyin: "yě", meaning: "cũng" },
  { id: 298, level: 1, topicId: "hsk1_t12", hanzi: "的", pinyin: "de", meaning: "trợ từ (sở hữu)" },
  { id: 299, level: 1, topicId: "hsk1_t12", hanzi: "喂", pinyin: "wèi", meaning: "aloo" },
  { id: 300, level: 1, topicId: "hsk1_t12", hanzi: "还", pinyin: "hái", meaning: "vẫn, còn" },
  { id: 301, level: 1, topicId: "hsk1_t12", hanzi: "吗", pinyin: "ma", meaning: "phải không" },
  { id: 302, level: 1, topicId: "hsk1_t12", hanzi: "对不起", pinyin: "duìbuqǐ", meaning: "xin lỗi" },
  { id: 303, level: 1, topicId: "hsk1_t12", hanzi: "太", pinyin: "tài", meaning: "quá, lắm" },
  { id: 304, level: 1, topicId: "hsk1_t12", hanzi: "呢", pinyin: "ne", meaning: "thì sao" },
  { id: 305, level: 1, topicId: "hsk1_t12", hanzi: "和", pinyin: "hé", meaning: "và" },
  { id: 306, level: 1, topicId: "hsk1_t12", hanzi: "真", pinyin: "zhēn", meaning: "thật sự, thật là" },
  { id: 307, level: 1, topicId: "hsk1_t12", hanzi: "非常", pinyin: "fēicháng", meaning: "vô cùng, rất (cao hơn 很)" },
  { id: 308, level: 1, topicId: "hsk1_t12", hanzi: "吧", pinyin: "ba", meaning: "nhé, đi, nha" },
  { id: 309, level: 1, topicId: "hsk1_t12", hanzi: "在", pinyin: "zài", meaning: "đang, ở, tại" },
  { id: 310, level: 1, topicId: "hsk1_t12", hanzi: "没", pinyin: "méi", meaning: "không, chưa" },
  { id: 311, level: 1, topicId: "hsk1_t12", hanzi: "和", pinyin: "hé", meaning: "cùng với, và" },
  { id: 312, level: 1, topicId: "hsk1_t12", hanzi: "正在", pinyin: "zhèngzài", meaning: "đang" },
  { id: 313, level: 1, topicId: "hsk1_t12", hanzi: "对不起", pinyin: "duìbuqǐ", meaning: "xin lỗi" },
  { id: 314, level: 1, topicId: "hsk1_t12", hanzi: "了", pinyin: "le", meaning: "rồi" },
  { id: 315, level: 1, topicId: "hsk1_t12", hanzi: "有点儿", pinyin: "yǒudiǎnr", meaning: "hơi, có chút" },
  { id: 316, level: 1, topicId: "hsk1_t12", hanzi: "再", pinyin: "zài", meaning: "lại, rồi mới" },
  { id: 317, level: 1, topicId: "hsk1_t12", hanzi: "了", pinyin: "le", meaning: "trợ từ hoàn thành" },
  { id: 318, level: 1, topicId: "hsk1_t12", hanzi: "都", pinyin: "dōu", meaning: "đều" },
];

const SENTENCE_DATA = [
  { id: 1, level: 1, pinyin: "Wǒ shì xuéshēng.", vietnamese: "Tôi là học sinh.", correctOrder: ["我", "是", "学生"] },
  { id: 2, level: 1, pinyin: "Tā shì wǒ bàba.", vietnamese: "Ông ấy là bố tôi.", correctOrder: ["他", "是", "我", "爸爸"] },
  { id: 3, level: 1, pinyin: "Tā shì lǎoshī.", vietnamese: "Cô ấy là giáo viên.", correctOrder: ["她", "是", "老师"] },
  { id: 4, level: 1, pinyin: "Wǒmen shì hǎo péngyou.", vietnamese: "Chúng tôi là bạn tốt.", correctOrder: ["我们", "是", "好朋友"] },
  { id: 5, level: 1, pinyin: "Zhè shì wǒ māma.", vietnamese: "Đây là mẹ tôi.", correctOrder: ["这", "是", "我", "妈妈"] },
  { id: 6, level: 1, pinyin: "Tā bú shì Zhōngguórén.", vietnamese: "Anh ấy không phải là người Trung Quốc.", correctOrder: ["他", "不是", "中国人"] },
  { id: 7, level: 1, pinyin: "Zhè shì yì běn shū.", vietnamese: "Đây là một quyển sách.", correctOrder: ["这", "是", "一", "本", "书"] },
  { id: 8, level: 1, pinyin: "Nà shì shéi de māo?", vietnamese: "Kia là con mèo của ai?", correctOrder: ["那", "是", "谁", "的", "猫"] },
  { id: 9, level: 1, pinyin: "Wáng lǎoshī shì Zhōngguórén.", vietnamese: "Cô Vương là người Trung Quốc.", correctOrder: ["王老师", "是", "中国人"] },
  { id: 10, level: 1, pinyin: "Tā shì wǒ de tóngxué.", vietnamese: "Cậu ấy là bạn học của tôi.", correctOrder: ["他", "是", "我的", "同学"] },
  { id: 11, level: 1, pinyin: "Jīntiān shì xīngqīyī.", vietnamese: "Hôm nay là thứ hai.", correctOrder: ["今天", "是", "星期一"] },
  { id: 12, level: 1, pinyin: "Zuótiān shì wǒ de shēngrì.", vietnamese: "Hôm qua là sinh nhật của tôi.", correctOrder: ["昨天", "是", "我的", "生日"] },
  { id: 13, level: 1, pinyin: "Wǒ yǒu yí gè gēge.", vietnamese: "Tôi có một người anh trai.", correctOrder: ["我", "有", "一个", "哥哥"] },
  { id: 14, level: 1, pinyin: "Tā yǒu hěn duō shū.", vietnamese: "Cô ấy có rất nhiều sách.", correctOrder: ["她", "有", "很", "多", "书"] },
  { id: 15, level: 1, pinyin: "Zhuōzi shang yǒu yí gè píngguǒ.", vietnamese: "Trên bàn có một quả táo.", correctOrder: ["桌子", "上", "有", "一个", "苹果"] },
  { id: 16, level: 1, pinyin: "Wǒ jiā yǒu sì kǒu rén.", vietnamese: "Nhà tôi có bốn người.", correctOrder: ["我", "家", "有", "四", "口", "人"] },
  { id: 17, level: 1, pinyin: "Xuéxiào lǐ yǒu hěn duō xuéshēng.", vietnamese: "Trong trường học có rất nhiều học sinh.", correctOrder: ["学校", "里", "有", "很多", "学生"] },
  { id: 18, level: 1, pinyin: "Tā méiyǒu diànnǎo.", vietnamese: "Anh ấy không có máy tính.", correctOrder: ["他", "没有", "电脑"] },
  { id: 19, level: 1, pinyin: "Nǐ yǒu Hànyǔ shū ma?", vietnamese: "Bạn có sách tiếng Hán không?", correctOrder: ["你", "有", "汉语", "书", "吗"] },
  { id: 20, level: 1, pinyin: "Yǐzi xià yǒu yì zhī gǒu.", vietnamese: "Dưới ghế có một con chó.", correctOrder: ["椅子", "下", "有", "一只", "狗"] },
  { id: 21, level: 1, pinyin: "Wǒ jiā yǒu yì zhī xiǎomāo.", vietnamese: "Nhà tôi có một con mèo con.", correctOrder: ["我", "家", "有", "一", "只", "小猫"] },
  { id: 22, level: 1, pinyin: "Bēizi lǐ yǒu shuǐ ma?", vietnamese: "Trong cốc có nước không?", correctOrder: ["杯子", "里", "有", "水", "吗"] },
  { id: 23, level: 1, pinyin: "Māma zài jiā zuòfàn.", vietnamese: "Mẹ đang nấu cơm ở nhà.", correctOrder: ["妈妈", "在", "家", "做饭"] },
  { id: 24, level: 1, pinyin: "Bàba zài yīyuàn gōngzuò.", vietnamese: "Bố làm việc ở bệnh viện.", correctOrder: ["爸爸", "在", "医院", "工作"] },
  { id: 25, level: 1, pinyin: "Lǎoshī zài xuéxiào ma?", vietnamese: "Thầy giáo có ở trường không?", correctOrder: ["老师", "在", "学校", "吗"] },
  { id: 26, level: 1, pinyin: "Wǒ zài Běijīng xué Hànyǔ.", vietnamese: "Tôi học tiếng Hán ở Bắc Kinh.", correctOrder: ["我", "在", "北京", "学", "汉语"] },
  { id: 27, level: 1, pinyin: "Tā xiànzài zài nǎr?", vietnamese: "Hiện tại anh ấy ở đâu?", correctOrder: ["他", "现在", "在", "哪儿"] },
  { id: 28, level: 1, pinyin: "Xiǎogǒu zài yǐzi xiàmiàn.", vietnamese: "Chú chó con ở dưới cái ghế.", correctOrder: ["小狗", "在", "椅子", "下面"] },
  { id: 29, level: 1, pinyin: "Shū zài zhuōzi shang.", vietnamese: "Sách ở trên bàn.", correctOrder: ["书", "在", "桌子", "上"] },
  { id: 30, level: 1, pinyin: "Tā zhèngzài tīng yīnyuè.", vietnamese: "Anh ấy đang nghe nhạc.", correctOrder: ["他", "正在", "听", "音乐"] },
  { id: 31, level: 1, pinyin: "Mèimei zài fángjiān kànshū.", vietnamese: "Em gái đang đọc sách trong phòng.", correctOrder: ["妹妹", "在", "房间", "看书"] },
  { id: 32, level: 1, pinyin: "Péngyou zài qiánbian děng wǒ.", vietnamese: "Bạn bè đang đợi tôi ở phía trước.", correctOrder: ["朋友", "在", "前边", "等", "我"] },
  { id: 33, level: 1, pinyin: "Wǒ xiǎng xué Zhōngwén.", vietnamese: "Tôi muốn học tiếng Trung.", correctOrder: ["我", "想", "学", "中文"] },
  { id: 34, level: 1, pinyin: "Nǐ xiǎng hē shénme?", vietnamese: "Bạn muốn uống gì?", correctOrder: ["你", "想", "喝", "什么"] },
  { id: 35, level: 1, pinyin: "Wǒ xiǎng qù shāngdiàn mǎi dōngxi.", vietnamese: "Tôi muốn đi cửa hàng mua đồ.", correctOrder: ["我", "想", "去", "商店", "买", "东西"] },
  { id: 36, level: 1, pinyin: "Míngtiān wǒ xiǎng kàn diànyǐng.", vietnamese: "Ngày mai tôi muốn xem phim.", correctOrder: ["明天", "我", "想", "看", "电影"] },
  { id: 37, level: 1, pinyin: "Tā huì shuō Hànyǔ.", vietnamese: "Anh ấy biết nói tiếng Hán.", correctOrder: ["他", "会", "说", "汉语"] },
  { id: 38, level: 1, pinyin: "Nǐ huì zuòfàn ma?", vietnamese: "Bạn biết nấu cơm không?", correctOrder: ["你", "会", "做饭", "吗"] },
  { id: 39, level: 1, pinyin: "Wǒ néng zuò zài zhèr ma?", vietnamese: "Tôi có thể ngồi ở đây không?", correctOrder: ["我", "能", "坐", "在", "这儿", "吗"] },
  { id: 40, level: 1, pinyin: "Tā bú huì xiě zhè ge zì.", vietnamese: "Anh ấy không biết viết chữ này.", correctOrder: ["他", "不会", "写", "这个", "字"] },
  { id: 41, level: 1, pinyin: "Māma xǐhuan chī píngguǒ.", vietnamese: "Mẹ thích ăn táo.", correctOrder: ["妈妈", "喜欢", "吃", "苹果"] },
  { id: 42, level: 1, pinyin: "Wǒ fēicháng xǐhuan zhè běn shū.", vietnamese: "Tôi vô cùng thích cuốn sách này.", correctOrder: ["我", "非常", "喜欢", "这", "本", "书"] },
  { id: 43, level: 1, pinyin: "Wǒmen qù xuéxiào kànshū ba.", vietnamese: "Chúng ta đến trường đọc sách đi.", correctOrder: ["我们", "去", "学校", "看书", "吧"] },
  { id: 44, level: 1, pinyin: "Xià gè xīngqī wǒ qù Běijīng.", vietnamese: "Tuần sau tôi đi Bắc Kinh.", correctOrder: ["下个", "星期", "我", "去", "北京"] },
  { id: 45, level: 1, pinyin: "Xiàwǔ nǐ qù nǎr?", vietnamese: "Buổi chiều bạn đi đâu?", correctOrder: ["下午", "你", "去", "哪儿"] },
  { id: 46, level: 1, pinyin: "Tā zuò chūzūchē qù huǒchēzhàn.", vietnamese: "Anh ấy đi taxi đến ga tàu hỏa.", correctOrder: ["他", "坐", "出租车", "去", "火车站"] },
  { id: 47, level: 1, pinyin: "Wǒ hé péngyou qù chī Zhōngguócài.", vietnamese: "Tôi cùng bạn đi ăn món ăn Trung Quốc.", correctOrder: ["我", "和", "朋友", "去", "吃", "中国菜"] },
  { id: 48, level: 1, pinyin: "Jīntiān wǒmen chī shénme?", vietnamese: "Hôm nay chúng ta ăn gì?", correctOrder: ["今天", "我们", "吃", "什么"] },
  { id: 49, level: 1, pinyin: "Qǐng hē zhè bēi chá.", vietnamese: "Mời uống tách trà này.", correctOrder: ["请", "喝", "这", "杯", "茶"] },
  { id: 50, level: 1, pinyin: "Fúwùyuán, wǒ xiǎng mǎi mǐfàn.", vietnamese: "Phục vụ, tôi muốn mua cơm trắng.", correctOrder: ["服务员", "我", "想", "买", "米饭"] },
  { id: 51, level: 1, pinyin: "Zhè ge xīguā hěn tián.", vietnamese: "Quả dưa hấu này rất ngọt.", correctOrder: ["这个", "西瓜", "很", "甜"] },
  { id: 52, level: 1, pinyin: "Wǒ zuótiān mǎi le yí jiàn yīfu.", vietnamese: "Hôm qua tôi đã mua một bộ quần áo.", correctOrder: ["我", "昨天", "买", "了", "一", "件", "衣服"] },
  { id: 53, level: 1, pinyin: "Zhè ge shǒujī duōshao qián?", vietnamese: "Chiếc điện thoại này bao nhiêu tiền?", correctOrder: ["这个", "手机", "多少", "钱"] },
  { id: 54, level: 1, pinyin: "Nà gè píngguǒ hěn guì.", vietnamese: "Quả táo kia rất đắt.", correctOrder: ["那", "个", "苹果", "很", "贵"] },
  { id: 55, level: 1, pinyin: "Jīntiān tiānqì hěn hǎo.", vietnamese: "Hôm nay thời tiết rất đẹp.", correctOrder: ["今天", "天气", "很", "好"] },
  { id: 56, level: 1, pinyin: "Míngtiān huì xiàyǔ ma?", vietnamese: "Ngày mai trời sẽ mưa không?", correctOrder: ["明天", "会", "下雨", "吗"] },
  { id: 57, level: 1, pinyin: "Běijīng de dōngtiān hěn lěng.", vietnamese: "Mùa đông ở Bắc Kinh rất lạnh.", correctOrder: ["北京", "的", "冬天", "很", "冷"] },
  { id: 58, level: 1, pinyin: "Wàimiàn tài rè le.", vietnamese: "Bên ngoài nóng quá rồi.", correctOrder: ["外面", "太", "热", "了"] },
  { id: 59, level: 1, pinyin: "Zhè ge dìfang hěn piàoliang.", vietnamese: "Nơi này rất đẹp.", correctOrder: ["这个", "地方", "很", "漂亮"] },
  { id: 60, level: 1, pinyin: "Nǐ de Hànyǔ hěn hǎo.", vietnamese: "Tiếng Hán của bạn rất tốt.", correctOrder: ["你", "的", "汉语", "很", "好"] },
  { id: 61, level: 1, pinyin: "Zhè jiàn yīfu tài dà le.", vietnamese: "Chiếc áo này to quá rồi.", correctOrder: ["这", "件", "衣服", "太", "大", "了"] },
  { id: 62, level: 1, pinyin: "Wǒ jīntiān hěn gāoxìng.", vietnamese: "Hôm nay tôi rất vui.", correctOrder: ["我", "今天", "很", "高兴"] },
  { id: 63, level: 1, pinyin: "Hànzì bú tài nán.", vietnamese: "Chữ Hán không khó lắm.", correctOrder: ["汉字", "不", "太", "难"] },
  { id: 64, level: 1, pinyin: "Nǐ jiào shénme míngzi?", vietnamese: "Bạn tên là gì?", correctOrder: ["你", "叫", "什么", "名字"] },
  { id: 65, level: 1, pinyin: "Tā shì shéi?", vietnamese: "Anh ấy là ai?", correctOrder: ["他", "是", "谁"] },
  { id: 66, level: 1, pinyin: "Nǐ jīnnián duō dà le?", vietnamese: "Năm nay bạn bao nhiêu tuổi rồi?", correctOrder: ["你", "今年", "多", "大", "了"] },
  { id: 67, level: 1, pinyin: "Xiànzài jǐ diǎn le?", vietnamese: "Bây giờ là mấy giờ rồi?", correctOrder: ["现在", "几", "点", "了"] },
  { id: 68, level: 1, pinyin: "Nǐ zěnme qù jīchǎng?", vietnamese: "Bạn đi đến sân bay bằng cách nào?", correctOrder: ["你", "怎么", "去", "机场"] },
  { id: 69, level: 1, pinyin: "Zhè běn shū zěnmeyàng?", vietnamese: "Quyển sách này thế nào?", correctOrder: ["这", "本", "书", "怎么样"] },
  { id: 70, level: 1, pinyin: "Tā wèishénme méi lái?", vietnamese: "Tại sao anh ấy không đến?", correctOrder: ["他", "为什么", "没", "来"] },
  { id: 71, level: 1, pinyin: "Nǐ kàn, nà shì shéi?", vietnamese: "Bạn nhìn xem, kia là ai?", correctOrder: ["你", "看", "那", "是", "谁"] },
  { id: 72, level: 1, pinyin: "Wǒ rènshi nà ge yīshēng.", vietnamese: "Tôi quen biết vị bác sĩ kia.", correctOrder: ["我", "认识", "那个", "医生"] },
  { id: 73, level: 1, pinyin: "Hěn gāoxìng rènshi nǐ.", vietnamese: "Rất vui được quen biết bạn.", correctOrder: ["很高兴", "认识", "你"] },
  { id: 74, level: 1, pinyin: "Qǐngwèn, xǐshǒujiān zài nǎr?", vietnamese: "Xin hỏi nhà vệ sinh ở đâu?", correctOrder: ["请问", "洗手间", "在", "哪儿"] },
  { id: 75, level: 1, pinyin: "Xièxie nǐ de bāngzhù.", vietnamese: "Cảm ơn sự giúp đỡ của bạn.", correctOrder: ["谢谢", "你", "的", "帮助"] },
  { id: 76, level: 1, pinyin: "Duìbuqǐ, wǒ chídào le.", vietnamese: "Xin lỗi, tôi đến muộn rồi.", correctOrder: ["对不起", "我", "迟到", "了"] },
  { id: 77, level: 1, pinyin: "Méi guānxi, qǐng jìn.", vietnamese: "Không sao cả, mời vào.", correctOrder: ["没关系", "请", "进"] },
  { id: 78, level: 1, pinyin: "Míngtiān jiàn.", vietnamese: "Hẹn ngày mai gặp.", correctOrder: ["明天", "见"] },
  { id: 79, level: 1, pinyin: "Xiànzài chà wǔ fēn bā diǎn.", vietnamese: "Bây giờ là tám giờ kém năm phút.", correctOrder: ["现在", "差", "五", "分", "八", "点"] },
  { id: 80, level: 1, pinyin: "Wǒ zǎoshang qī diǎn qǐchuáng.", vietnamese: "Buổi sáng tôi thức dậy lúc bảy giờ.", correctOrder: ["我", "早上", "七", "点", "起床"] },
  { id: 81, level: 1, pinyin: "Wǎnshang wǒmen yìqǐ kàn diànshì.", vietnamese: "Buổi tối chúng tôi cùng nhau xem tivi.", correctOrder: ["晚上", "我们", "一起", "看", "电视"] },
  { id: 82, level: 1, pinyin: "Tā zài Běijīng zhù le sān nián.", vietnamese: "Anh ấy đã sống ở Bắc Kinh ba năm.", correctOrder: ["他", "在", "北京", "住", "了", "三", "年"] },
  { id: 83, level: 1, pinyin: "Wǒ mǎi le liǎng gè dà píngguǒ.", vietnamese: "Tôi đã mua hai quả táo to.", correctOrder: ["我", "买", "了", "两", "个", "大", "苹果"] },
  { id: 84, level: 1, pinyin: "Zhè shì dì-yī cì lái Zhōngguó.", vietnamese: "Đây là lần đầu tiên đến Trung Quốc.", correctOrder: ["这", "是", "第一", "次", "来", "中国"] },
  { id: 85, level: 1, pinyin: "Wǒmen dōu shì dàxuéshēng.", vietnamese: "Chúng tôi đều là sinh viên đại học.", correctOrder: ["我们", "都", "是", "大学", "生"] },
  { id: 86, level: 1, pinyin: "Tā yě xǐhuan tī zúqiú.", vietnamese: "Anh ấy cũng thích đá bóng.", correctOrder: ["他", "也", "喜欢", "踢", "足球"] },
  { id: 87, level: 1, pinyin: "Dìdi bǐ wǒ xiǎo liǎng suì.", vietnamese: "Em trai nhỏ hơn tôi hai tuổi.", correctOrder: ["弟弟", "比", "我", "小", "两", "岁"] },
  { id: 88, level: 1, pinyin: "Kuài yào xiàyǔ le.", vietnamese: "Trời sắp mưa rồi.", correctOrder: ["快", "要", "下雨", "了"] },
];

const DataStore = {
  getEnabledLevels() {
    return HSK_LEVELS.filter((level) => level.enabled);
  },
  getLevel(id) {
    return HSK_LEVELS.find((level) => level.id === Number(id)) || null;
  },
  getTopicsByLevel(levelId) {
    return TOPICS.filter((topic) => topic.level === Number(levelId));
  },
  getTopic(topicId) {
    return TOPICS.find((topic) => topic.id === topicId) || null;
  },
  getVocab({ level, topicId, search } = {}) {
    const query = (search || "").trim().toLowerCase();
    return VOCAB_DATA.filter((word) => {
      if (level != null && word.level !== Number(level)) return false;
      if (topicId && word.topicId !== topicId) return false;
      if (!query) return true;
      return (
        word.hanzi.includes(search.trim()) ||
        word.pinyin.toLowerCase().includes(query) ||
        word.meaning.toLowerCase().includes(query)
      );
    });
  },
  getVocabById(id) {
    return VOCAB_DATA.find((word) => word.id === Number(id)) || null;
  },
  getSentences({ level } = {}) {
    if (level == null) return SENTENCE_DATA;
    return SENTENCE_DATA.filter((s) => s.level === Number(level));
  },
  getSentenceById(id) {
    return SENTENCE_DATA.find((s) => s.id === Number(id)) || null;
  },
};
